services:
  web:
    image: gl-resources-lp:latest
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - IPWHOIS_ENDPOINT=${IPWHOIS_ENDPOINT}
      - DOH_ENDPOINT=${DOH_ENDPOINT}
      - NEXT_PUBLIC_HUBSPOT_SCRIPT_URL=${NEXT_PUBLIC_HUBSPOT_SCRIPT_URL}
      - NEXT_PUBLIC_HUBSPOT_MEETING_URL=${NEXT_PUBLIC_HUBSPOT_MEETING_URL}
      - NEXT_PUBLIC_THANKYOU_VIDEO_ID=${NEXT_PUBLIC_THANKYOU_VIDEO_ID}