name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            -t gl-resources-lp:latest \
            -f ./Dockerfile \
            .

      - name: Save and Compress Image
        run: |
          echo "Saving image..."
          docker save gl-resources-lp:latest | gzip > gl-resources-lp.tar.gz
          echo "Image size:"
          du -sh gl-resources-lp.tar.gz

      # - name: Prepare docker-compose file
      #   run: cp docker-compose.prod.yml docker-compose.yml

      - name: Create .env file
        run: | 
          touch .env
          echo "NEXT_PUBLIC_SITE_URL=${{secrets.NEXT_PUBLIC_SITE_URL}}" >> .env
          echo "IPWHOIS_ENDPOINT=${{secrets.IPWHOIS_ENDPOINT}}" >> .env
          echo "DOH_ENDPOINT=${{secrets.DOH_ENDPOINT}}" >> .env
          echo "NEXT_PUBLIC_HUBSPOT_SCRIPT_URL=${{secrets.NEXT_PUBLIC_HUBSPOT_SCRIPT_URL}}" >> .env
          echo "NEXT_PUBLIC_HUBSPOT_MEETING_URL=${{secrets.NEXT_PUBLIC_HUBSPOT_MEETING_URL}}" >> .env
          echo "NEXT_PUBLIC_THANKYOU_VIDEO_ID=${{secrets.NEXT_PUBLIC_THANKYOU_VIDEO_ID}}" >> .env

      - name: Transfer Files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: ".env,gl-resources-lp.tar.gz"
          target: ${{ github.event.repository.name }}

      - name: Deploy Containers on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/${{ github.event.repository.name }}
            
            echo 'Loading image...'
            docker load -i gl-resources-lp.tar.gz
            
            echo 'Restarting containers with docker compose...'
            docker compose up -d --force-recreate --remove-orphans
            
            echo 'Cleaning up transfer archives...'
            rm -f gl-resources-lp.tar.gz
            
            echo 'Cleaning up dangling/unused docker images...'
            docker image prune -f
            
            echo 'Deployment successful!'